export const bounce: string;
export const flash: string;
export const jump: string;
export const pulse: string;
export const rotate90: string;
export const rubberBand: string;
export const shakeX: string;
export const spin: string;
export const zoomIn: string;
